# Generated by Django 5.2.9 on 2026-01-05 05:42

import django.core.validators
import django.db.models.deletion
import hitcount.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inn', models.CharField(max_length=25, verbose_name='INN')),
                ('qisqacha_nomlanishi', models.CharField(max_length=255, verbose_name='Qisqacha nomlanishi')),
                ('qisqacha_nomlanishi_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое наименование')),
                ('qisqacha_nomlanishi_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Қисқача номланиши (Кирилл)')),
                ('tashkiliy_huquqiy_shakli', models.CharField(max_length=100, verbose_name='Tashkiliy-huquqiy shakli')),
                ('tashkiliy_huquqiy_shakli_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организационно-правовая форма')),
                ('tashkiliy_huquqiy_shakli_uz_cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ташкилий-ҳуқуқий шакли (Кирилл)')),
                ('tashkilot_faoliyatining_holati', models.CharField(max_length=255, verbose_name='Tashkilot faoliyatining holati')),
                ('tashkilot_faoliyatining_holati_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Состояние деятельности организации')),
                ('tashkilot_faoliyatining_holati_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ташкилот фаолиятининг ҳолати (Кирилл)')),
                ('tasischi', models.CharField(max_length=255, verbose_name='Tasischi')),
                ('tasischi_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Учредитель')),
                ('tasischi_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тасисчи (Кирилл)')),
                ('hudud', models.CharField(choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent_viloyati', 'Toshkent viloyati'), ('andijon_viloyati', 'Andijon viloyati'), ('buxoro_viloyati', 'Buxoro viloyati'), ('fargona_viloyati', "Farg'ona viloyati"), ('jizzax_viloyati', 'Jizzax viloyati'), ('xorazm_viloyati', 'Xorazm viloyati'), ('namangan_viloyati', 'Namangan viloyati'), ('navoiy_viloyati', 'Navoiy viloyati'), ('qashqadaryo_viloyati', 'Qashqadaryo viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi"), ('samarqand_viloyati', 'Samarqand viloyati'), ('sirdaryo_viloyati', 'Sirdaryo viloyati'), ('surxondaryo_viloyati', 'Surxondaryo viloyati')], max_length=50, verbose_name='Hudud')),
                ('tuman', models.CharField(max_length=255, verbose_name='Tuman')),
                ('tuman_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('tuman_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Туман (Кирилл)')),
                ('manzil', models.CharField(max_length=255, verbose_name='Manzil')),
                ('manzil_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('manzil_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Манзил (Кирилл)')),
                ('davlat_ulishi', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Davlat ulushi (%)')),
                ('xojalik_ulishi', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Xo'jalik ulushi (%)")),
            ],
            options={
                'verbose_name': 'Tashkilot haqida',
                'verbose_name_plural': 'Tashkilot haqida',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('content', tinymce.models.HTMLField(verbose_name='Matn')),
                ('content_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('content_uz_cyrl', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Матн (Кирилл)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Qaror',
                'verbose_name_plural': 'Qarorlar',
                'ordering': ['-created_date'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='InteractiveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('about', models.TextField(verbose_name="Ma'lumot")),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('about_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='Маълумот (Кирилл)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Interaktiv xizmat',
                'verbose_name_plural': 'Interaktiv xizmatlar',
                'ordering': ['-created_date'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='JobVacancyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номи (Кирилл)')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Ish o'rinlari bo'limlari",
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('full_name_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тўлиқ исм (Кирилл)')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('position_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лавозим (Кирилл)')),
                ('reception_time', models.CharField(max_length=255, verbose_name='Qabul vaqtlari')),
                ('reception_time_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время приема')),
                ('reception_time_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Қабул вақтлари (Кирилл)')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('about', models.TextField(verbose_name="Umumiy ma'lumot")),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='Общая информация')),
                ('about_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='Умумий маълумот (Кирилл)')),
                ('labor_activity', models.TextField(verbose_name='Mehnat faoliyati')),
                ('labor_activity_ru', models.TextField(blank=True, null=True, verbose_name='Трудовая деятельность')),
                ('labor_activity_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='Меҳнат фаолияти (Кирилл)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Rahbariyat',
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('main_image', models.ImageField(upload_to='news/', verbose_name='Asosiy rasm')),
                ('content', tinymce.models.HTMLField(verbose_name='Matn')),
                ('content_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('content_uz_cyrl', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Матн (Кирилл)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_date'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('korsatilayotgan_xizmatlar', models.IntegerField(default=0, verbose_name="Ko'rsatilayotgan xizmatlar soni")),
                ('hududiy_boshqarmalar_soni', models.IntegerField(default=0, verbose_name='Hududiy boshqarmalar soni')),
                ('nasos_stansiyalar_soni', models.IntegerField(default=0, verbose_name='Nasos stansiyalari soni')),
                ('xodimlar', models.IntegerField(default=0, verbose_name='Xodimlar soni')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': "Statistika ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номи (Кирилл)')),
            ],
            options={
                'verbose_name': 'Ish turi',
                'verbose_name_plural': 'Ish turlari',
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номи (Кирилл)')),
                ('link', models.URLField(verbose_name='Havola')),
                ('icon', models.ImageField(upload_to='links_icons/', verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Foydali havola',
                'verbose_name_plural': 'Foydali havolalar',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('location', models.CharField(max_length=255, verbose_name='Manzil')),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('location_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Манзил (Кирилл)')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='Тавсиф (Кирилл)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='core.jobvacancydepartment', verbose_name="Bo'lim")),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='core.leadership', verbose_name='Rahbariyat')),
                ('type_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='core.typeofwork', verbose_name='Ish turi')),
            ],
            options={
                'verbose_name': "Ish o'rini",
                'verbose_name_plural': "Ish o'rinlari",
                'ordering': ['-created_date'],
            },
        ),
    ]
