# Generated by Django 5.2.9 on 2026-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leadership/', verbose_name='Rasm'),
        ),
    ]
