# Generated by Django 5.2.9 on 2026-01-05 06:25

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leadership_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='content_uz_cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Матн (Кирилл)'),
        ),
        migrations.AlterField(
            model_name='interactiveservice',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='interactiveservice',
            name='about_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='interactiveservice',
            name='about_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Маълумот (Кирилл)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='description_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Тавсиф (Кирилл)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name="Umumiy ma'lumot"),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='about_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='about_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Умумий маълумот (Кирилл)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='labor_activity',
            field=ckeditor.fields.RichTextField(verbose_name='Mehnat faoliyati'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='labor_activity_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='labor_activity_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Меҳнат фаолияти (Кирилл)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz_cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Матн (Кирилл)'),
        ),
    ]
