# Generated by Django 5.2.9 on 2026-01-05 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_decision_content_alter_decision_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_uz_cyrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория (Кирилл)'),
        ),
        migrations.AddField(
            model_name='news',
            name='minutes_to_read',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name="O'qish vaqti (daqiqa)"),
        ),
    ]
