# Generated by Django 5.2.9 on 2026-03-06 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_news_category_news_category_ru_news_category_uz_cyrl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номи (Кирилл)')),
                ('leader', models.CharField(max_length=255, verbose_name='Rahbar')),
                ('leader_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Руководитель')),
                ('leader_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рахбар (Кирилл)')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('position_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лавозим (Кирилл)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Tavsif')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz_cyrl', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Тавсиф (Кирилл)')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('phone_ru', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('phone_uz_cyrl', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон (Кирилл)')),
                ('reception_days', models.CharField(max_length=255, verbose_name='Qabul kunlari')),
                ('reception_days_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дни приема')),
                ('reception_days_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Қабл кунлари (Кирилл)')),
            ],
            options={
                'verbose_name': 'Markaziy apparat',
                'verbose_name_plural': 'Markaziy apparat',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fayl')),
                ('published_date', models.DateField(verbose_name='Nashr qilingan sana')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Tashkilot hujjatlari',
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('number', models.CharField(max_length=100, verbose_name='Raqami')),
                ('number_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер')),
                ('number_uz_cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рақами (Кирилл)')),
                ('date', models.DateField(verbose_name='Sana')),
                ('file', models.FileField(upload_to='laws/', verbose_name='Fayl')),
            ],
            options={
                'verbose_name': 'Qonun',
                'verbose_name_plural': 'Qonunlar',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Tavsif')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz_cyrl', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Тавсиф (Кирилл)')),
                ('file', models.FileField(upload_to='open_data/', verbose_name='Fayl')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Ochiq ma'lumot",
                'verbose_name_plural': "Ochiq ma'lumotlar",
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RegionalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номи (Кирилл)')),
                ('region', models.CharField(choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent_viloyati', 'Toshkent viloyati'), ('andijon_viloyati', 'Andijon viloyati'), ('buxoro_viloyati', 'Buxoro viloyati'), ('fargona_viloyati', "Farg'ona viloyati"), ('jizzax_viloyati', 'Jizzax viloyati'), ('xorazm_viloyati', 'Xorazm viloyati'), ('namangan_viloyati', 'Namangan viloyati'), ('navoiy_viloyati', 'Navoiy viloyati'), ('qashqadaryo_viloyati', 'Qashqadaryo viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi"), ('samarqand_viloyati', 'Samarqand viloyati'), ('sirdaryo_viloyati', 'Sirdaryo viloyati'), ('surxondaryo_viloyati', 'Surxondaryo viloyati')], max_length=50, verbose_name='Viloyat')),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('address_uz_cyrl', models.CharField(blank=True, max_length=500, null=True, verbose_name='Манзил (Кирилл)')),
                ('leader', models.CharField(max_length=255, verbose_name='Rahbar')),
                ('leader_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Руководитель')),
                ('leader_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рахбар (Кирилл)')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('phone_ru', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('phone_uz_cyrl', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон (Кирилл)')),
            ],
            options={
                'verbose_name': 'Hududiy boshqarma',
                'verbose_name_plural': 'Hududiy boshqarmalar',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сарлавҳа (Кирилл)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Tavsif')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz_cyrl', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Тавсиф (Кирилл)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Vazifa va funksiya',
                'verbose_name_plural': 'Vazifalar va funksiyalar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
